### ISSUE TITLE
new module: raven assembler

### ISSUE THREAD

**Issue by fmalmeida** [nf-core/modules#1042]
I think it would be good to have a module for [raven assembler](https://github.com/lbcb-sci/raven)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by fmalmeida** [comment]
Here @mjmansfi, I've started an issue about raven module. I will start fresh as discussed and then make a PR for review 🙂

**Comment by fmalmeida** [comment]
Hi @mjmansfi,

I believe I have created a prototype that may already work 😄 , but I am not sure if I am following all the standards. Currently it is on a [raven branch in my personal fork](https://github.com/fmalmeida/modules/tree/raven).

You said something about some small automated tests that you already had. How we can proceed? Should I already start a PR and we work directly on the PR?

**Comment by mjmansfi** [comment]
**Re: test data**

I have simulated Nanopore reads for SARS-CoV-2 made with the tool [DeepSimulator](https://github.com/liyu95/DeepSimulator). I'm not actually sure `test-datasets` are using SARS-CoV-2 anymore though - is this correct? I can send a link to the read sets I've got if you want though, just let me know.

**Re: the module**
It looks good to me! I do have a question, the current version would not support `raven`'s GPU options. Do you think this matters? I haven't used GPU-accelerated `raven`; I also haven't used GPU acceleration in `nf-core`-style modules (e.g. is there a GPU process tag?

I have ran GPU-accelerated Nextflow processes work with `docker` and `singularity`, works great, but it might be annoying with `conda`.

**Comment by fmalmeida** [comment]
**Re: test data**

When you said in slack I understood that we could somehow automatize the test with some github actions available in nf-core. But, now I understood that the small dataset is to test locally, right? If it is that, I already have a small dataset (10X e. coli) that I can assemble here as a test.

**Re: GPU**

Although the raven GPU existed, and today it still exists but is hidden, I don't think it matters for the following:

1. GPU usage is not standardised in nf-core modules
2. As you said, GPU could be annoying to automatize some in some profiles
3. Raven, in their paper, compare itself using CPU and, already with CPU they had good run times, being faster than flye and only slower than shasta. So I believe it is ok to maintain its usage with CPU

**Comment by mjmansfi** [comment]
**Re: test data**

Check out the testing guidelines in the docs: [https://nf-co.re/developers/adding_modules](https://nf-co.re/developers/adding_modules)

I didn't notice it, but the testing scheme in your branch contains only the initialized module defaults. Part of the `nf-core/modules` scheme is a large set of automated testing that gets triggered when you commit to `nf-core/modules` (or maybe it's only on PRs). The module test suite automatically pulls data from [nf-core/test-datasets](https://github.com/nf-core/test-datasets/tree/modules), the `modules` branch specifically. 

So you also need to contribute test data that is capable of ensuring your `raven` process still works and hasn't broken for some reason. Check the docs for instructions, it's a little difficult to explain. Basically you need to write a one-process workflow that invokes your `raven` process on test data from the [nf-core/test-datasets](https://github.com/nf-core/test-datasets/tree/modules) repository. Then you use the `nf-core` tool's built-in functions to trigger the test. The testing includes checking the hash of the output files and the `nf-core` tool fills these in for you automatically. It checks whether the hash is consistent over multiple runs because some tools are non-deterministic (in which case, I think the test only checks whether the output file exists). 

Check out my comment here and the subsequent discussion for why existing test data are not suitable: [https://nfcore.slack.com/archives/CJRH30T6V/p1620635126375900](https://nfcore.slack.com/archives/CJRH30T6V/p1620635126375900)

I tried a lot of things to get any assembler to actually work with SARS-CoV-2 data but real data are all amplicon based, so _de novo_ assemblers were not liking it (highly uneven coverage and so on). So, I tried simulating reads with the tool I mentioned. This works, but the issue I then had was the tests couldn't consistently run within the 2GB memory limit of the Github actions. I spent a long time trying to find test data that could 1. actually be assembled by `flye`, `raven`, and `shasta`, and 2. succeed within a 2GB memory limit.

However, this is old news from several months ago and things change quickly! I heard that the testing scheme and the test data itself has changed since then. I don't know where to look for more information - maybe double check the open PRs and see how they are pulling test data in `nf-core/modules` - or start a thread in the `#modules` Slack channel.

**Comment by fmalmeida** [comment]
I will read more about it then to understand it.

About the data, I believe we could try to use the data that Unicycler has put under their test_data that are some reads from a Shigella plasmids.

Maybe the assembly of these reads would stay below 2 Gb. I can give it a try locally.
