### ISSUE TITLE
Shrinking test data to a minimal, coherent set

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/modules#242]
For the vast majority of tools, we need similar test data, like fastq, bams etc.
Often is required to use different files from the same organism. Currently, for many test datasets, it is not clear how they have been generated (e.g. which organism, fasta, gtf ...) which limits their usage.

I would therefore propose to try and limit the test data to one single organism, and to remove files which are named like 'test_r1.fastq' because nobody knows what they are anymore.

**Comment by Emiller88** [comment]
Just going to repost this from slack because I didn't know there was an issue.

I would vote we do one of two options(both use [bfg](https://rtyley.github.io/bfg-repo-cleaner/), and just because keeping data files in git repos is a personal pet peeve):

1. Use bfg to remove all the history of the data files(or change them to git-lfs) then delete them and use the file('https://github.com/smithlabcode/preseq/raw/master/data/SRR1003759_5M_subset.mr', checkIfExists: true format for all the tests. Then we can pull whatever that module calls for from the nf-core test-data, from the repos of the software(which has been really handy). You won't be able to get started working on a plane though.

2. Run bfg and change all the data files to git-lfs, then change them to a single organism.

As @grst pointed out
>(just be aware that using these tools will change all commit ids)

**Comment by KevinMenden** [comment]
Okay, as discussed on Slack (ping @drpatelh ), we want to make everything properly organized. Just a few things to decide:

Structure:
* generic
* genomics
    * organism
        * fasta
            * test.fasta
 
With the above structure we would not have any naming of the organism in the actual file anymore (`test.fasta`) because that would be taken care of by the parent directory. Advantage (?) is that all files of the different organisms are named the same. Disadvantage is that we loose any potentially helpful information in the name, e.g. the exact genome version. This would therefore require careful documentation in the README.md.
Personally I prefer having some kind of meaningful file names over complete standardization between organisms.

I will furthermore try to remove one of the two sarscov2 sequences and associated files. 

The generic folder is not properly organized currently because there are still some files we have to get rid of. If we end up needing the E.coli data after all, we'll move that into `genomics` as well. 

Okay so maybe we write down any other thoughts about this here as well so it is easier to track :)

**Comment by drpatelh** [comment]
My bad, I am a lazy issue poster at the best of times due to barrages of Slack messages 😅 

Ok so this is what I originally posted on Slack:
"Maybe we go with `test_PE.bam` (name sorted PE BAM),  `test_PE.sorted.bam` (coordinate sorted PE BAM), `test_SE.sorted.bam` (coordinate sorted SE BAM) and associated indices? Given that the data will be organised by organism I don't think we need to prefix it with the organism name? Could then have a similar naming convention for other organisms? e.g. `ecoli/bam/test_PE.bam`."

Are we likely to be using different genome versions from the same organism that will affect the naming? For the purposes of the tests I think its more important that the filenames contain enough description as to what they contain e.g. PE/SE data, methylated, spliced alignments etc.

The only reason I am suggesting a complete standardisation is because the naming convention will become a free for all again when we start adding new test data and we will be back to where we started. If we can at least point to a "best practice" set of file structure then that would be easier to grasp for newcomers too. That's why I think its a good idea to agree on something now.

**Comment by phue** [comment]
So shall we then add `test_methylated_PE.bam` and `test_methylated_PE.sorted.bam` for DNA methylation data aswell?

**Comment by drpatelh** [comment]
Yes, that sounds good 👍🏽 Will you be able to rustle something up against the SARS-CoV-2 genome? 

Jusst thought of another reason for naming standardisation e.g. when things eventually fill out, if we need to larger files for testing a particular module then we can just switch the genome name and the paths will be the same.

**Comment by KevinMenden** [comment]
Okay those are good points you got me convinced. Then let's try tidy everything up with the correct names :) 

I can't get STAR to run with the virus genome so far, so we might have to have some E.coli stuff in there as well. The main reason I have two right now is because I couldn't get a GTF for that one `tests/data/generic/fasta/NC_010473.fa` 
@phue you happen to have that somewhere? Because the methylation data uses that genome I think.

**Comment by phue** [comment]
I was using Ecoli mainly because there we already have BS-seq testdata [here](https://github.com/nf-core/modules/tree/master/tests/data/fastq/methylated_dna).
I _guess_ I could also simulate such reads for the SARS-CoV-2 genome

**Comment by KevinMenden** [comment]
Okay, I think in this case it is fine to stick with the data we have for now, but of course if you could simulate something that would be awesome :) 

I just want to integrate this into the repo as fast as possible so that incoming modules can use this data.

Okay so then we go with a structure like this `genomics/organims/data_type/test.<ending>` 
With some additional qualifiers in the file name that can be standardized, like `PE`, `SE`, `sorted` and so on. 
If that is fine with everybody then I will implement this for the Sarscov2 data, and make an E.coli folder for now as well. I will leave the generic stuff as is for now.

@drpatelh anything else I should change/ you can think of right now? Because I will have to go through every single module again, wanna make sure I don't have to do that again :)

**Comment by drpatelh** [comment]
Let's be explicit with PE and SE e.g. `single_end` and `paired_end`. Other than that I can't think of anything. Ping me on Slack if you have any edge cases that don't fit that and we can iron out the details.

**Comment by KevinMenden** [comment]
Great, I'll get to it then :)
