### ISSUE TITLE
new module: Redbean

### ISSUE THREAD

**Issue by diegomics** [nf-core/modules#2573]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

tool: https://github.com/ruanjue/wtdbg2

**Comment by asp8200** [comment]
@diegomics : It's been four years since the latest release of wtdbg2 - is the request to make this into a nf-module still relevant?

I had a look at the [README](https://github.com/ruanjue/wtdbg2) for the tool. From the README, I got the vague impression that it should be possible to run something like

wtdbg2 -x rs -g4.6m -t16 -i reference.fasta.gz -fo prefix

where the `reference.fasta.gz` comes from [here](http://www.cbcb.umd.edu/software/PBcR/data/selfSampleData.tar.gz). The command ran, but then it produced some dubious looking files.

**Comment by diegomics** [comment]
Yep. I think is not relevant anymore. Closing this long-forgotten issue now. Thanks for the heads-up
