### ISSUE TITLE
Module tests

### ISSUE THREAD

**Issue by drpatelh** [nf-core/modules#4]
There will be various tests we can perform on individual module files...how far we go and how we implement this is up for discussion.

1) Test and parse module file to create documentation for information about the tools used in the process e.g home-page links etc  
2) Test and parse the content of the process via NF e.g. `input:`, `output:` and `script:`
3) Test the module works on `include` with a vanilla template script
4) Test the actual process command works by bundling containers from biocontainers as default and testing the execution - this will also require the appropriate test data to be hosted somewhere for CI tests. This could be a can of worms as we should be able to expect contributors to test this anyway (@Sven?)

**Comment by sven1103** [comment]
I think we have to distinguish between a module/process test and documentation. Maybe an own issue for docs?

Regarding **module tests**: You can think of a module as a set of processes and functions. Each process and function has a particular responsibility.  Both consume input data as arguments, execute a task, and can return an output. And it would be nice to test if such a unit executes as expected. That is the fundamental idea of a Unit Test :)

So ideally, a module has a corresponding module test suite, that does exactly that:

1. It sets up the environment and set up the preconditions for the unit (here a Nextflow process or function) **(given)**
2. It executes the unit (the process or function) **(when)**
3. It checks assertions about the expected behaviour **(then)**

How can this look like? Assume we have a module file `myModule.nf` that contains a process `myProcess()`. A Test Suite could be a file `myModuleTest.nf` that actually includes the process from `myModule.nf` and correctly sets up the environment (loading a container, defines URLs to source data, etc.). Assertions could be realised by just routing the output from the process to a `assertionProcess()` and check the output there. This process should fail, if at least one assertion was false. 

Maybe we can just set up a proof-of-concept test for one of your modules, and see if this works out?

**Comment by ewels** [comment]
Need to think about where we keep test data and how it is organised.

Suggestion: still use `nf-core/test-data` but reorganise. Keep everything in one branch, have a set of data under `common` that can be used by multiple tools. Stuff that is specific to a single tool can then go in subdirectories that mirror `nf-core/modules`.

**Comment by Emiller88** [comment]
So can we consider this one closed now that we've got so many tests we hit the GitHub actions limit?

**Comment by drpatelh** [comment]
I think we can indeed 😁 🎉
