### ISSUE TITLE
[FEATURE] clustalo/align doesn't support profile alignment

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/modules#7091]
### Is your feature request related to a problem? Please describe

I'd like to use clustalo to do profile alignment, i.e. using the `-profile1` argument. This isn't supported by the current module.

Moreover, there are plenty of other path arguments that are not supported, and the `tree` path doesn't seem to be used by the module.

### Describe the solution you'd like

@luisas @JoseEspinosa and @lrauschning : I'd like to add non-obligatory params to the module for all file arguments to the program listed under "Sequence Input" in the help text. I'd add a test for profile alignment with `--profile1` and `--hmm-in` but since I'm not familiar with how the other modes work that would have to wait. Or, is it better to add just these two paths to the module?

(Paths listed under "Clustering" could perhaps be implemented in a `clustalo/clustering` module?)

**Comment by luisas** [comment]
Hi @erikrikarddaniel, 

concerning the missing usage of the guide tree - thanks for spotting! This is a bug!

This makes it a bug in our pipeline too (nf-core/multiplesequencealign) so I am happy to take care of that now.
Are you already taking care of the guide tree? I will open a PR soon otherwise  - I have some vested interest to have it in ASAP cause we are planning to submit a paper soon and would have to be bug free :) 

I am not overly confident either on how these paths work, but if they are optional input files, it makes perfect sense to me to have the option to use them in the module. The user would then have to know which exact arguments to use :)

**Comment by erikrikarddaniel** [comment]
I'm on the other params (I'm adding all four: `--hmm-in`, `--hmm-batch`, `--profile1` and `--profile2`, but will only test number 1 and 3) so please take care of the guide tree. Happy to look at the PR when it's ready so I can merge it in with my work.

**Comment by luisas** [comment]
fantastic, here goes the PR: https://github.com/nf-core/modules/pull/7092
