### ISSUE TITLE
Add Editor Config lint back in

### ISSUE THREAD

**Issue by drpatelh** [nf-core/modules#77]
I commented out the Editor config linting https://github.com/nf-core/modules/pull/76/commits/082c582258fc16c2afc32f94af157ac8faaf12cc but it would be good to fix and add this back in. Possibly in one go to get all of the tests passing again.

**Comment by Emiller88** [comment]
The comments are breaking this
```
/*
 * Tidy up and join elements of a list to return a path string
 */
```
After running `eclint fix` on everything it still throws errors about `invalid indent size: 1, expected: 0` on the block comments.

**Comment by grst** [comment]
Maybe this helps: 
https://github.com/jedmao/eclint#support-for-doc-comments

**Comment by Emiller88** [comment]
@grst Good catch!

Per https://github.com/jedmao/eclint/issues/226, `eclint` is no longer maintained. 

https://github.com/editorconfig-checker/editorconfig-checker.javascript#readme is however, and it works with the comment blocks out of the box. PR incoming.

**Comment by grst** [comment]
I think prettier supports editorconfig out-of-the-box:

> If options.editorconfig is true and an .editorconfig file
<https://editorconfig.org/> is in your project, Prettier will parse it and
convert its properties to the corresponding Prettier configuration. This
configuration will be overridden by .prettierrc, etc. Currently, the
following EditorConfig properties are supported

https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options

**Comment by drpatelh** [comment]
Thanks guys! Those comments can be changed to support default options in editor linting tools by the way. Don't really use these normally so opinion neutral as to which one we go for. Ideally, something that has longevity.

**Comment by Emiller88** [comment]
@grst I definitely prefer prettier myself. I was just getting at using it for all the linting would be cool (md, and yaml) and having a nextflow plugin! I was also hoping to avoid adding a `.prettierrc` to the project though, because I don't think the conversation has been had to possibly move yaml or md over. I don't think we should bother with it unless a nextflow-plugin is created. I'll look into it in a few weeks.

As I thought I can't find a way to just run editorconfig on files that don't have a parser with prettier.
