### ISSUE TITLE
new module: canu

### ISSUE THREAD

**Issue by d4straub** [nf-core/modules#823]
I think it would be good to have a module for [canu](https://bioconda.github.io/recipes/canu/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

nf-core/bacass is using a [local canu module](https://github.com/nf-core/bacass/blob/master/modules/local/canu.nf)

This is also mentioned in https://github.com/nf-core/bacass/issues/61

**Comment by scorreard** [comment]
Going to work on this module

**Comment by scorreard** [comment]
Started to work on this module but I cannot pass the test because none of the Nanopore / PacBio data seems to have enough overlapping reads to generate the assembly

Feel free to use the files from here if you want to give it a go : https://github.com/scorreard/modules/tree/newmodule_canu/modules/nf-core

**Comment by scorreard** [comment]
Progressed on the module, it works on Gitpod but fails the new module test (probably a memory issue).
I don't know if it's good enough to review and merge.
https://github.com/nf-core/modules/pull/2824
