### ISSUE TITLE
[BUG] Empty VCF on testdata for mutect2

### ISSUE THREAD

**Issue by fbdtemme** [nf-core/modules#870]
When running the mutect2 test for tumor-normal analysis the test runs fine, but an empty VCF file is generated.
This causes issues downstream when trying the use the output of GATK4_MUTECT2 in 
for example GATK4_MERGEVCFS.

It would be great to have a test dataset that produces actual results so downstream tools can rely on that data as well.

**Steps to reproduce:**
```
export PROFILE=docker
nextflow run tests/modules/gatk4/mutect2 -entry test_gatk4_mutect2_tumor_normal_pair -c tests/config/nextflow.config
```
Inspect VCF file generated by GATK4_MUTECT2...

**Comment by FriederikeHanssen** [comment]
This is fixed, right?

**Comment by GCJMackenzie** [comment]
I haven't had anything to do with the ASCAT or ControlFREEC modules, but all the others should be using the new datasets now. So should be generating files that aren't empty now

**Comment by jasmezz** [comment]
Hi there!

Looks like the issue is solved. Are you still planning to check if all module tests are working fine?
If not, you can ignore this message and we’ll close your PR in about 2 weeks.
If you think this is still relevant, you can also add it to the [hackathon2023 project board](https://github.com/orgs/nf-core/projects/41).

Cheers
the nf-core maintainers
