### ISSUE TITLE
Support multiple nextflow versions in CI

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#88]
Should we support multiple nextflow versions in the CI? If so which ones. See https://github.com/nf-core/modules/pull/85/commits/8cd635f757d6d9b2d7c051cc94959caa601a903a

**Comment by drpatelh** [comment]
Good question 👍 Maybe we run against the first stable DSL2 release i.e. `20.07.1` as well as the latest? The pipeline CI tests do something similar but in this instance it ensures that the modules are working across the full spectrum of DSL2 releases. If we encounter breaking changes we can bump the minimum version used for the tests.

**Comment by drpatelh** [comment]
Note the matrix tests will look something like this:
https://github.com/nf-core/rnaseq/blob/bc5fc76f40b2da6082a854927184c9d6e5060393/.github/workflows/ci.yml#L23

**Comment by Emiller88** [comment]
Gotcha! Thanks I couldn't find the right value for "latest"!

**Comment by drpatelh** [comment]
As a result of the changes introduced in https://github.com/nf-core/modules/pull/109 we now have the ability to directly download Singularity containers, however, this functionality was added in an edge release i.e. `20.11.0-edge`. This means I had to change the version of Nextflow we use for the module CI as shown in [this commit](https://github.com/nf-core/modules/pull/109/commits/992232b340b4fe60929937a8efa40f6fc7f180ec). After the next stable Nextflow release we should revert the CI to using `nxf_version: [<STABLE_RELEASE>, ""]` again. Note the `""` in that list will pull the latest stable release which at this point doesn't contain the functionality we need which is why I removed it in that commit.

**Comment by drpatelh** [comment]
Hmmmm...after the recent (and superdooper) surge in modules and the failure of all of the current tests to be triggered with one NF version (due to matrix limit of 256), I think testing multiple NF versions is overkill until something changes. At which point feel free to re-open this issue.
