### ISSUE TITLE
Add tests for preseq

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#99]

**Comment by sruthipsuresh** [comment]
For the preseq module, would we need to have another input file to use?
When testing it, preseq fails with the test files we have in both the bed and bam format as they have low read counts. 

From the user manual:
preseq lc_extrap can fail to estimate the curve if there are not enough reads in the
aligned bam file for the calculation. The error reported is:
ERROR: max count before zero is less than min required count (4), sample not sufficiently deep or duplicates removed

Additionally, there's an error in the module where the $bam file is not preceded by a -bam prefix (since the default is a bed file).

**Comment by drpatelh** [comment]
Good question @sruthipsuresh ! Yes, Preseq hasn't been updated in quite a while now and I doubt it will be anytime soon...

Does it fail for single-end and paired-end data? Given the issues you mentioned I think it would be good enough to get it passing with single-end data only. May need to change the test data for this if required but as far as I remember I saw these issues mainly with paired-end data.

**Comment by sruthipsuresh** [comment]
It fails for both types of data unfortunately. I also tried creating a sorted bed file from the test bam files that we have already (as described [here](https://github.com/nf-core/methylseq/issues/96#issuecomment-716986814)), but that fails as well.

The single-end test does work with [this sample file](https://github.com/smithlabcode/preseq/blob/master/data/SRR1106616_5M_subset.bam) from the preseq repo- should this be used as the test data instead then?

**Comment by Emiller88** [comment]
I think that's a good option, I couldn't find any test stuff last night in their repo good job!

Ah this was just what I was looking for too! https://www.nextflow.io/docs/edge/script.html#http-ftp-files

You should be able to use something like https://github.com/smithlabcode/preseq/raw/master/data/SRR1003759_5M_subset.mr for each of the files for input.

So 

```
mr = file('https://github.com/smithlabcode/preseq/raw/master/data/SRR1003759_5M_subset.mr')
```

**Comment by sruthipsuresh** [comment]
I'll do that instead of adding the file to the input folder directly! Thank you!
